apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: simple-team
  description: Simple team develops simple-service
spec:
  type: team
  profile:
    displayName: Simple team
    email: SimpleTeam@example.com
  children: []
